version: '3'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  user-server:
    image: bes99/user-server
    container_name: user-server
    ports:
      - "8080:8080"
    networks:
      - user-server-network
    depends_on:
      - redis
