
server:
  port: 0
spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false
    compatibility-verifier:
      enabled: false


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.34.94.202:8761/eureka